In [30]:
import scipy.io as sio
import numpy as np

In [30]:
def save_as_gml(nodes,edges):
    f = open('graph.gml','w')
    f.write('graph [\n')
    f.write('  node [\n')
    for i in nodes:
        f.write('    id '+str(i)+'\n')
        f.write('    label '+str(i)+'\n')

        f.write('  ]\n')

    for i in edges:
        f.write('  edge [\n')
        f.write('    source '+str(i[0])+'\n')
        f.write('    target '+str(i[1])+'\n')
        f.write('    label '+str(0)+'\n')
        f.write('  ]\n')
    f.write(']\n')

def save_text(edges):
    with open("graph.txt","w") as f:
        for edge in edges:
            if int(edge[0]) < (edge[1]):
                f.write(str(edge[0])+" "+str(edge[1])+" {}\n")
            else:
                f.write(str(edge[1])+" "+str(edge[0])+" {}\n")


        




In [17]:
import scipy.io as sio
map_key=sio.loadmat("../map_key.mat")

edges=[]
edge_sort=[]
vertices=[]
for edge in map_key["map_key"][0]:
    edges.append(edge[0].split("+"))
# print(edges)
for i in range(64984):
    vertices.append(i)

# save_as_gml(nodes=vertices,edges=edges)


for edge in edges:
    edge_sort.append((int(edge[0]),edge[1]) if int(edge[0]) < int(edge[1]) else (int(edge[1]),edge[0]))
edge_sort
edge_sort.sort()
#
edge_dict={}
for edge in edge_sort:
    if edge[0] not in edge_dict.keys():
        edge_dict[edge[0]]=[int(edge[1])]
    else:
        edge_dict[edge[0]].append(int(edge[1]))

for key,value in edge_dict.items():
    
    edge_dict[key]=sorted(value)
    

edge_list=[]
for key,value in edge_dict.items():
    for i in value:
        edge_list.append((int(key),i))

# save_text(edge_list)
print(len(edge_list))
# save_text(edge_dict)

37732


In [20]:
import scipy.io as sio
edge_key=sio.loadmat("../edge_key.mat")["key"][0]
edge_value=sio.loadmat("../edge_value.mat")["value"][0]

print(edge_key)


[array(['100+0'], dtype='<U5') array(['100+25572'], dtype='<U9')
 array(['1000+0'], dtype='<U6') ... array(['9974+0'], dtype='<U6')
 array(['9974+17134'], dtype='<U10') array(['9974+17135'], dtype='<U10')]


In [18]:
#映射节点关系
node_unique=[]
for i in edge_list:
    if i[0] not in node_unique:
        node_unique.append(i[0])
    if i[1] not in node_unique:
        node_unique.append(i[1])
# print(node_unique)
node_dic={}
for i in range(len(node_unique)):
    node_dic[node_unique[i]]=i

edge_list_trans=[]
for edge in edge_list:
    #去除自环的部分节点，不添加到内容中
    # if node_dic[edge[0]]==node_dic[edge[1]]:
    #     continue
    edge_list_trans.append((node_dic[edge[0]],node_dic[edge[1]]))
# print(edge_list_trans)

In [5]:
#获取逆映射列表
dic_reverse=dict((v,k) for k,v in node_dic.items())
print(dic_reverse)

# print(edge_dict)

{0: 0, 1: 4, 2: 6, 3: 14, 4: 22, 5: 24, 6: 28, 7: 29, 8: 31, 9: 32, 10: 33, 11: 34, 12: 35, 13: 36, 14: 37, 15: 51, 16: 52, 17: 57, 18: 73, 19: 74, 20: 80, 21: 100, 22: 101, 23: 112, 24: 115, 25: 142, 26: 143, 27: 144, 28: 145, 29: 146, 30: 148, 31: 149, 32: 150, 33: 153, 34: 158, 35: 159, 36: 168, 37: 181, 38: 182, 39: 184, 40: 185, 41: 191, 42: 197, 43: 198, 44: 200, 45: 201, 46: 202, 47: 203, 48: 204, 49: 205, 50: 218, 51: 221, 52: 222, 53: 223, 54: 225, 55: 236, 56: 238, 57: 239, 58: 240, 59: 249, 60: 250, 61: 251, 62: 253, 63: 254, 64: 255, 65: 256, 66: 257, 67: 258, 68: 271, 69: 275, 70: 276, 71: 281, 72: 291, 73: 293, 74: 294, 75: 296, 76: 305, 77: 306, 78: 308, 79: 309, 80: 310, 81: 311, 82: 312, 83: 323, 84: 324, 85: 329, 86: 346, 87: 349, 88: 354, 89: 355, 90: 357, 91: 358, 92: 359, 93: 360, 94: 361, 95: 362, 96: 363, 97: 364, 98: 365, 99: 390, 100: 395, 101: 404, 102: 405, 103: 406, 104: 407, 105: 408, 106: 409, 107: 410, 108: 411, 109: 412, 110: 413, 111: 414, 112: 415, 113

In [27]:

def save_text(edges):
    with open("graph2.txt","w") as f:
        for edge in edges:
            # if edge[0]==edge[1]:
            #     continue
            if int(edge[0]) < (edge[1]):
                f.write(str(edge[0])+" "+str(edge[1])+"\n")
            else:
                f.write(str(edge[1])+" "+str(edge[0])+"\n")

In [28]:
save_text(edge_list)

In [21]:
import networkx as nx
import matplotlib.pyplot as plt

G=nx.Graph()
with open("graph1.txt","r" ) as f:
    line=f.readline()
    while line:
        edge=line.strip().split(" ")
        G.add_edge(edge[0],edge[1])
        line=f.readline()
# nx.draw(G,with_labels=G.nodes())
# plt.show()
# plt.savefig("graph1.png")

In [22]:
nx.read_edgelist("graph1.txt")

In [31]:

# G1=nx.to_undirected(G1)


In [24]:
G2=nx.read_edgelist('graph1.txt', create_using=nx.DiGraph())
# G2=nx.to_undirected(G2)

In [12]:
nx.write_gml(G2,"graph2.gml")

In [33]:
G1=nx.read_edgelist('graph2.txt', create_using=nx.DiGraph())
print(list(nx.simple_cycles(G1)))

[['308'], ['791'], ['833'], ['834'], ['872'], ['2744'], ['2779'], ['2812'], ['2848'], ['2855'], ['2886'], ['2945'], ['3005'], ['3029'], ['3054'], ['3080'], ['3244'], ['3263'], ['3274'], ['3314'], ['3356'], ['3360'], ['5019'], ['6279'], ['7710'], ['12330'], ['12412'], ['16894'], ['17455'], ['27583'], ['27645'], ['29153'], ['30399'], ['30457'], ['32529'], ['32854'], ['35337'], ['35371'], ['35402'], ['35520'], ['35548'], ['35571'], ['35594'], ['35703'], ['35796'], ['35842'], ['35843'], ['35861'], ['36837'], ['37898'], ['37899'], ['37948'], ['41901'], ['41936'], ['42104'], ['42163'], ['45114'], ['48605'], ['49361'], ['51541'], ['55856'], ['55985'], ['57124'], ['60578'], ['62337'], ['63271'], ['63306'], ['63428'], ['64075']]


In [16]:
G2.remove_edges_from(nx.selfloop_edges(G2))
G2=nx.free(G2)
print(G2.is_connected())

AttributeError: module networkx has no attribute free

In [ ]:
with open("graph1.txt","r" ) as f:
    line=f.readline()
    while line:
        edge=line.strip().split(" ")
        G2.add_edge(edge[0],edge[1])
        line=f.readline()

In [3]:
with open("result_graph1.txt","r" ) as f:
    line=f.readlines()
print([x.strip() for x in line])


['0', '6240', '719', '111', '6825', '8964', '729', '6839', '720', '92', '6237', '108', '675', '6881', '6886', '5425', '137', '6254', '96', '7822', '706', '7831', '95', '7368', '122', '6238', '721', '663', '798', '6146', '5424', '5414', '664', '847', '123', '6239', '741', '705', '126', '5422', '121', '6902', '6301', '6887', '146', '12', '6880', '753', '6818', '732', '136', '6871', '826', '110', '107', '780', '6290', '160', '693', '6863', '6785', '6352', '755', '6236', '6274', '6224', '215', '5401', '6966', '94', '6267', '793', '708', '148', '6867', '6936', '6865', '868', '11571', '718', '11564', '6223', '6263', '6938', '6888', '6174', '109', '12000', '6147', '5412', '781', '6874', '6276', '106', '6339', '6241', '31', '7349', '6827', '147', '6275', '3975', '695', '112', '135', '750', '77', '647', '91', '6852', '6250', '6872', '761', '6264', '782', '6895', '6843', '707', '47', '6873', '6253', '125', '666', '6208', '770', '6855', '176', '11580', '773', '6266', '6879', '6220', '723', '214',

In [7]:
#读取结果文件，获取原始节点

with open("result_graph1.txt","r" ) as f:
    line=f.readlines()
nodes=[x.strip() for x in line]
node_original=[]
for node in nodes:
    node_original.append(dic_reverse[int(node)])
print(node_original)


[0, 32907, 2912, 414, 35462, 44547, 2942, 35490, 2913, 359, 32904, 411, 2812, 35596, 35618, 27540, 511, 32958, 363, 38764, 2882, 38791, 362, 37438, 461, 32905, 2914, 2778, 3129, 32528, 27539, 27516, 2779, 3260, 462, 32906, 2973, 2881, 465, 27537, 460, 35663, 33144, 35619, 558, 35, 35595, 3003, 35433, 2945, 510, 35570, 3210, 413, 410, 3080, 33101, 608, 2850, 35545, 35337, 33325, 3005, 32903, 33051, 32857, 834, 27487, 35825, 361, 33008, 3107, 2884, 560, 35549, 35766, 35547, 3301, 60004, 2911, 59978, 32856, 33004, 35768, 35620, 32696, 412, 63272, 32529, 27514, 3081, 35573, 33053, 409, 33279, 32908, 149, 37393, 35464, 559, 33052, 16861, 2852, 415, 509, 3000, 306, 2744, 358, 35517, 32954, 35571, 3029, 33005, 3082, 35640, 35494, 2883, 203, 35572, 32957, 464, 2781, 32803, 3055, 35520, 697, 60030, 3058, 33007, 35594, 32853, 2916, 833, 2745, 609, 512, 33002, 27532, 33283, 3028, 27533, 561, 32750, 35641, 33148, 32695, 44966, 2941, 35491, 35546, 655, 311, 792, 32953, 654, 44942, 45468, 364, 2975,

In [16]:

node_form_mat=node = sio.loadmat('../node.mat')
print(node["ans"][0][0][0].T)
node_matrix=node["ans"][0][0][0].T
with open("node_result.txt","w" ) as f:
    for i in node_original:
        f.write(",".join([str(x) for x in node_matrix[i]])+"\n")

[[ -9.203461 -39.663757  26.138397]
 [-22.236511 -38.524216  59.275558]
 [-47.786926  -5.991791  34.802025]
 ...
 [ 60.034302 -34.216621 -11.112442]
 [ 59.615402 -33.664948  -9.494114]
 [ 58.297832 -35.000595 -10.267822]]
